// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "users/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CreateEndpoint endpoint.Endpoint
	HelloEndpoint  endpoint.Endpoint
	ByeEndpoint    endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.UsersService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		ByeEndpoint:    MakeByeEndpoint(s),
		CreateEndpoint: MakeCreateEndpoint(s),
		HelloEndpoint:  MakeHelloEndpoint(s),
	}
	for _, m := range mdw["Create"] {
		eps.CreateEndpoint = m(eps.CreateEndpoint)
	}
	for _, m := range mdw["Hello"] {
		eps.HelloEndpoint = m(eps.HelloEndpoint)
	}
	for _, m := range mdw["Bye"] {
		eps.ByeEndpoint = m(eps.ByeEndpoint)
	}
	return eps
}
